version: '3'

services:

  mysql-development:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testos
      MYSQL_DATABASE: jobboard
    ports:
      - "3308:3308"
    volumes:
      - jobbdd:/var/lib/mysql
volumes:
  jobbdd: